/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VehicleBookingRouteImport } from './routes/vehicle-booking'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as InvitationsRouteImport } from './routes/invitations'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesCategoryRouteImport } from './routes/services.$category'
import { Route as PhotographyServiceRouteImport } from './routes/photography.$service'
import { Route as InvitationsCodeRouteImport } from './routes/invitations.$code'

const VehicleBookingRoute = VehicleBookingRouteImport.update({
  id: '/vehicle-booking',
  path: '/vehicle-booking',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationsRoute = InvitationsRouteImport.update({
  id: '/invitations',
  path: '/invitations',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesCategoryRoute = ServicesCategoryRouteImport.update({
  id: '/$category',
  path: '/$category',
  getParentRoute: () => ServicesRoute,
} as any)
const PhotographyServiceRoute = PhotographyServiceRouteImport.update({
  id: '/$service',
  path: '/$service',
  getParentRoute: () => PhotographyRoute,
} as any)
const InvitationsCodeRoute = InvitationsCodeRouteImport.update({
  id: '/$code',
  path: '/$code',
  getParentRoute: () => InvitationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/invitations': typeof InvitationsRouteWithChildren
  '/photography': typeof PhotographyRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vehicle-booking': typeof VehicleBookingRoute
  '/invitations/$code': typeof InvitationsCodeRoute
  '/photography/$service': typeof PhotographyServiceRoute
  '/services/$category': typeof ServicesCategoryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/invitations': typeof InvitationsRouteWithChildren
  '/photography': typeof PhotographyRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vehicle-booking': typeof VehicleBookingRoute
  '/invitations/$code': typeof InvitationsCodeRoute
  '/photography/$service': typeof PhotographyServiceRoute
  '/services/$category': typeof ServicesCategoryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/invitations': typeof InvitationsRouteWithChildren
  '/photography': typeof PhotographyRouteWithChildren
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vehicle-booking': typeof VehicleBookingRoute
  '/invitations/$code': typeof InvitationsCodeRoute
  '/photography/$service': typeof PhotographyServiceRoute
  '/services/$category': typeof ServicesCategoryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/gallery'
    | '/invitations'
    | '/photography'
    | '/services'
    | '/sitemap.xml'
    | '/vehicle-booking'
    | '/invitations/$code'
    | '/photography/$service'
    | '/services/$category'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/gallery'
    | '/invitations'
    | '/photography'
    | '/services'
    | '/sitemap.xml'
    | '/vehicle-booking'
    | '/invitations/$code'
    | '/photography/$service'
    | '/services/$category'
  id:
    | '__root__'
    | '/'
    | '/contact'
    | '/gallery'
    | '/invitations'
    | '/photography'
    | '/services'
    | '/sitemap.xml'
    | '/vehicle-booking'
    | '/invitations/$code'
    | '/photography/$service'
    | '/services/$category'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  InvitationsRoute: typeof InvitationsRouteWithChildren
  PhotographyRoute: typeof PhotographyRouteWithChildren
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VehicleBookingRoute: typeof VehicleBookingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vehicle-booking': {
      id: '/vehicle-booking'
      path: '/vehicle-booking'
      fullPath: '/vehicle-booking'
      preLoaderRoute: typeof VehicleBookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitations': {
      id: '/invitations'
      path: '/invitations'
      fullPath: '/invitations'
      preLoaderRoute: typeof InvitationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$category': {
      id: '/services/$category'
      path: '/$category'
      fullPath: '/services/$category'
      preLoaderRoute: typeof ServicesCategoryRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/photography/$service': {
      id: '/photography/$service'
      path: '/$service'
      fullPath: '/photography/$service'
      preLoaderRoute: typeof PhotographyServiceRouteImport
      parentRoute: typeof PhotographyRoute
    }
    '/invitations/$code': {
      id: '/invitations/$code'
      path: '/$code'
      fullPath: '/invitations/$code'
      preLoaderRoute: typeof InvitationsCodeRouteImport
      parentRoute: typeof InvitationsRoute
    }
  }
}

interface InvitationsRouteChildren {
  InvitationsCodeRoute: typeof InvitationsCodeRoute
}

const InvitationsRouteChildren: InvitationsRouteChildren = {
  InvitationsCodeRoute: InvitationsCodeRoute,
}

const InvitationsRouteWithChildren = InvitationsRoute._addFileChildren(
  InvitationsRouteChildren,
)

interface PhotographyRouteChildren {
  PhotographyServiceRoute: typeof PhotographyServiceRoute
}

const PhotographyRouteChildren: PhotographyRouteChildren = {
  PhotographyServiceRoute: PhotographyServiceRoute,
}

const PhotographyRouteWithChildren = PhotographyRoute._addFileChildren(
  PhotographyRouteChildren,
)

interface ServicesRouteChildren {
  ServicesCategoryRoute: typeof ServicesCategoryRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesCategoryRoute: ServicesCategoryRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  InvitationsRoute: InvitationsRouteWithChildren,
  PhotographyRoute: PhotographyRouteWithChildren,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VehicleBookingRoute: VehicleBookingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
